insert into tour_package(code, name) values
('BC', 'Backpack Cal'),
('CC', 'California Calm'),
('CH', 'California Hot Spring'),
('CY', 'Cicle California'),
('DS', 'From Desert to Sea'),
('KC', 'Kids California'),
('NW', 'Nature Watch'),
('SC', 'Snowboard Cali'),
('TC', 'Taste of California');

insert into tour (tour_package_code, title, blurb, description, bullets, difficulty, duration, price, region, keywords) values
(
    'BC',
    'Big Sur Retreat',
    'Big Sur is big country. The Big Sur Retreat takes you to the most majestic part of the Pacific Coast and show you the secret trails.',
    'The region know as Big Sur is like Yosemite''s younger cousin, with all the redwood scaling, rock climbing and, best of all, hiking that the larger park has to offer. Robison Jeffers once said, "Big Sur is the greatest meeting of land and sea in the world," but the highlights are only accessible on foot. Our 3-day tour allows you to choose from multiple hikes led by experienced guides during the day, while comfortably situated in the evenings at the historic Big Sur River Inn. Take a tranquil walk to the coastal waterfall at Julia Pfeiffer Burns State Par or hike to the Married Redwoods. If you''re prepared for a more strenuous climb, try Ollason''s Peak in Toro Park. An optional 4th day includes admission to the Henry Miller Library and the Point Reyes Lighthouse.',
    'Accommodations at the historic Big Sur River Inn, Privately guided hikes through any of the 5 surrounding national parks, Picnic lunches prepared by the River Inn kitchen, Complimentary country breakfast, Admission to the Henry Miller Library and the Point Reyes Lighthouse',
    'Medium',
    '3 days',
    '750',
    'Central Coast',
    'Hiking, National Parks, Big Sur'
),
(
    'BC',
    'In the Steps of John Muir',
    'Follow in the steps on John Muir, famous naturalist and founder of the Sierra Club, and walk the same trails he helped blaze in and around Yosemite National Park.',
    'John Muir famously walked from San Francisco to Yosemite, an astounding 300 miles, and this tour is designed to trace his steps-- at least part of the way. This tour is not for the faint of heart though. This is a true backpacker''s adventure, 37 miles in 3 days. Along the way, you''ll bear witness to the classic monuments of Yosemite, such as Vernal Falls, Nevada Falls, Half Dome, Cathedral Peak, Tuolumne Meadows and Mt. Lyell. At Nevada Falls, the trail becomes narrow and from then on, you''ll be privy to a "secret" Yosemite, including a rarely seen face of Half Dome. John Muir Trail tickets are required- and hard to come by- but Explore California has you covered. We''ll also provide a checklist so that you come prepared with the right equipment and a seasoned guide for your tour.',
    'Guided hike of the first 37 miles of the John Muir Trail, Reserved campsites, Organic and unexpectedly delicious prepared trail meals, Overview of Yosemite''s history and iconic vistas, Wilderness survival lessons',
    'Difficult',
    '3 days',
    '600',
    'Northern California',
    'Hiking, National Parks, Yosemite, John Muir, Camping'
),
(
    'BC',
    'The Death Valley Survivor''s Trek',
    'Hot stuff? Need more of a challenge? Take this tour to the hottest place in North America: Death Valley.',
    'This 2 day, 1 night tour takes you deep into the heart of Death Valley National Park. Due to extreme temperatures (120 degrees and higher) in the summer months, this tour is only offered November through April. This overnighter is no picnic though. Our guide will lead you on a 12 mile, off-trail hike down Death Valley Wash and into the backcountry for an overnight, hard terrain camping. Luckily, 12 miles takes you out of range of almost any city lights, something that draws thousands of star gazers to Death Valley ever year. If you can survive the 12 miles back, take advantage of the location to stop in at Scotty''s Castle, a genuine castle built by the eccentric and wealthy Walter Scott for his wife. This tour will make you truly appreciate modern luxuries.',
    '24-mile roundtrip hike through the Death Valley Wash, Backcountry camping, Fireside dinner and trail snacks provided, Stargazing and local wildlife highlighted, Tour  mysterious Scotty''s Castle',
    'Difficult',
    '2 days',
    '250',
    'Varies',
    'Hiking, Desert, Camping, Mojave, Death Valley'
),
(
    'BC',
    'The Mt. Whitney Climbers Tour',
    'Climb to the sky! The Mt. Whitney Climbers Tour takes you to the top of this 14,000 ft. of mountain in 4 days- our longest and most strenuous backpacking tour.',
    'Backpackers and hikers taking the Mt. Whitney Climbers Tour won''t need hooks and rappelling gear, but they will need to be on the look out for majestic sunrises, giant granite peaks and everything from brown bears to marmots. You''ll approach the towering peak from the trailhead on the western face, starting 6,000 feet above sea level. The Mt. Whitney Trail extends 11 miles and another 8 feet up to the peak. While no expensive training is required, you''ll still need planning, permits, and preparation. Explore California will set you up with a trail permit, a two night camping pass, and an expert guide. We''ll also help outfit you with the correct gear and make sure you are prepared for the length and elevation gain of the climb.',
    '22-mile roundtrip hike to the Mt. Whitney peak, 4 day hiking permit and 2 night camping permit included, Hiking tips and gear preparation provided from Peaked Supplies, Co., 1 nights lodging in Lone Pine',
    'Difficult',
    '4 days',
    '650',
    'Northern California',
    'Hiking, Climbing, Backpacking, Mt. Whitney'
),
(
    'BC',
    'Channel Islands Excursion',
    'The chain known as the Channel Islands offer some of the most diverse and unique landscape on the Pacific coast. No motor vehicles are allowed on the islands, which makes this daytrip hiking package the best and most interesting way to visit.',
    'The Channel Islands Excursion starts with a ferry from beautiful Ventura to the nearest island in the strand, Santa Cruz. You''ll spend the day wandering the rocky coasts, sea anemone and barnacle studded shoreline, and wildflower-strewn meadows of the islands. Visit the herd of wild buffalo housed on Santa Catalina and keep an eye peeled for the endangered island fox. Take a break for lunch on Catalina in the quaint, turn of the century styled Avalon and make sure to visit the Art Deco Catalina Casino. Before ferrying home, visit the botanical gardens or climb to one of the islands high points and do some inexpensive whale watching. Blue whale season extends the late spring through summer months. (The Whaling Tour, run by Island Packers, is also available for an additional cost.)',
    'Round-trip ferry from Ventura CA to Santa Cruz Island, Lunch provided in Avalon, Tour the art deco Catalina Casino, Whale watching package optional',
    'Easy',
    '1 day',
    '150',
    'Southern California',
    'Channel Islands, Boating, Whale watching, Hiking'
),
(
    'CC',
    'Day Spa Package',
    'Trying to pack some serious relaxation into a short timeframe? Try our Day Spa Package, a full 8 hour immersive experience in seductive the Ojai Valley that will ease away months'' worth of tension.',
    'The Day Spa Package: it''s all in the name. One day, one spa, but not just any day or any other spa. The Ojai Valley Inn & Spa is recognized by Trip Advisor as the World'' #1 spa and among the top 10 by USA Today. Your day of relaxation starts with a kuyam, a treatment combing cleansing desert clay, dry heat, inhalation and Chumash guided meditation. Choose from among several massage services, from Swedish to deep tissue, and body treatments, including the refreshing Pixie Tangerine & Pomegranate Scrub. Finish with a lavender manicure and pedicure or a "gentleman''s facial." Couples can enjoy joint massages, and expectant mothers should treat themselves to one of the nurturing prenatal treatments. In total, the package includes 5 straight hours of treatments, reserving time for a delicious spa lunch and time to linger by one of the many pools. This day will be one you think of for weeks.',
    '5 solid hours of spa treatments, Choose a massage, skin care offering, body treatment and a special luxury salon service, Dine at the Spa or choose from the poolside menu, Take  a complimentary class at the Artist''s Cottage or from one of the Spa''s Mind & Body instructors',
    'Easy',
    '1 day',
    '550',
    'Southern California',
    'Spa, Relaxation, Ojai, Art, Yoga'
),
(
    'CC',
    'Restoration Package',
    'The Restoration Package is a 2 day balm for the tired soul. Choose from among three destinations that uniquely combine world-class spa services and attention to the spirit, in locations of unparalleled natural beauty.',
    'California is no stranger to luxury (think Rodeo Drive) but we also offer a myriad of ways to not only pamper the body, but the spirit as well. Choose from among 3 options designed to help you relax and restore in the Restoration Package. Reconnect with nature and with yourself at the San Juan Spa, our Orange County Oasis; go backwoods, literally, on our Yosemite Yoga Retreat; or take comfort in our Napa Valley Validation spa sessions. Perfect for couples, the tireless mother or father you want to thank, or just yourself, this tour will immerse you in serenity.',
    'Choice of 3 different spa resorts, 1 full day of pampering, Luxury hotel accommodations, Hiking in Yosemite, Wine making in Napa',
    'Easy',
    '2 days',
    '900',
    'Varies',
    'Spa, Relaxation, Art, Yoga'
),
(
    'CC',
    'Huntington Library and Pasadena Retreat Tour',
    'This package is perfect for those who want to be pampered, but don''t just want to rest on their laurels all day. Stimulate your mind visiting the Huntington Library''s art and gardens and then settle back for some dining and primping at the Beauty Bar.',
    'This package is a rewarding for the mind and the soul. Visit the grounds of the incredible Huntington Library and Gardens, with over 200 acres of roses, waterways, cactus gardens and other exotic species. Have lunch in the famous Tea Room and then go inside the fabulous Art Deco buildings to survey the art collection. Afterwards, visit the Beauty Bar''s Pasadena location and enjoy a meal and drinks while having your nails buffed and your feet soaked.',
    'Admission to the Huntington Library and Gardens, Lunch in the Huntington''s Tea Room, Dinner at the Beauty Bar, Choice of three "mini" treatments at the Beauty Bar',
    'Easy',
    '1 day',
    '225',
    'Southern California',
    'Spa, Relaxation, Art, Yoga'
),
(
    'CH',
    'Avila Beach Hot springs',
    'Spend a weekend in a rustic log cabin, within walking distance of the historic Avila Hot Springs and minutes from the beach.',
    'Chumash have occupied Avila Beach for centuries, but it wasn''t until the late 19th century that the rest of California realized its ideal climate, proximity to the ocean and artesian springs made Avila Beach an ideal resort town. The hot springs in Avila are really unique, creating pools that hover at a natural 104 degrees, which draws aficionados from far and wide. You''ll stay at the historic Avila Hot Springs Resort, situated between oak-covered foothills that keep the morning fog away and make a natural year round air conditioner, which will enhance a nice morning, afternoon, or evening swim. This package include a two night stay in a private cabin above the springs, and a 3 day pass to the fresh water pool and 400 sq feet hot mineral pool. Optional day trips include two hour kayaking tours (we love the Cave Expedition) from Central Coast Kayaks and docent-led trips from the Point San Luis Lighthouse down the Pechos Trail.',
    '2 nights in a private cabin at the Avila Hot Springs Resort (includes a full kitchen), 3 day pass to the resort''s fresh water and hot springs pools, Complimentary continental breakfast, Kayaking or hiking expedition in downtown Avila Beach',
    'Easy',
    '3 days',
    '1000',
    'Central Coast',
    'Hot springs, hiking, cabin, beach, kayaking, hiking'
),
(
    'CH',
    'Matilija Hot springs',
    'Visit the Matilija Sanctuary, located above the tranquil Ojai Valley, and indulge in the waters that flow from the natural sulfur springs.',
    'Matilija Hot Springs has long been known to locals in this small community as a place to take a hot midnight dip in the middle of winter or a leisurely summer day, leaping between the sulfur pools and the cold creek nearby. Matilija Sanctuary, however, contains private springs that can only be accessed by special guests, including members of Explore California. Choose from a 3 or 4 day stay. Besides the complimentary nightly fireside music and the on-site crafts lodge other activities include day trips to downtown Ojai for shopping in it''s Spanish revival style arcade and hiking in the East End, an Eden-esque experience if we''ve ever had one.',
    'Private guest house at the Matilija Sanctuary, Complimentary use of the crafts lodge, Access to the private hot springs, steps away from a snow-fed creek only, Continental breakfast served with local organically grown nuts and fruits',
    'Easy',
    '3 days',
    '1000',
    'Central Coast',
    'Hot springs, Ojai, hiking, swimming, rustic, nature'
),
(
    'CY',
    'Amgen Tour of California Special',
    'This year only, we’re also offering a special package that allows serious cyclists to follow behind a competitor in the AMGEN bike race, a race that mimics the conditions in the Tour de France. Spots are limited so reserve your seat now!',
    'The AMGEN Tour of California is the largest cycling event in the US, over 750 miles and includes cycling world champions, Tour de France competitors, and Olympic athletes. It''s an 8-leg tour, designed to mimic the various conditions in the Tour de Trance, and Explore California has the unique pleasure of being able to offer 50 of our members spots behind the peloton, or main group of racers, on two legs of the two. This is a special, one-time only offer. Customers should be in physical and mental shape to complete this two-week ride. Be prepared to complete a detailed questionnaire about skill level and any existing health problems.',
    'Follow the main group of rider''s for two legs of Amgen''s Tour of California, Ride alongside Olympic athletes Tour de France competitors and professional cyclists, Enjoy car-free California roadways, Pace led by experienced and well trained professional cyclists, Lodging and meals included',
    'Medium',
    '6 days',
    '2500',
    'Varies',
    'Cycling'
),
(
    'DS',
    '2 Days Adrift the Salton Sea',
    'The Salton Sea, 25% saltier than the Pacific, has been a tourist destination since the 1920s. See what attracts people to this desert oasis.',
    'The Salton Sea is saltier than the Pacific, an unusual feat for inland body of water. And even though its salinity has risen over the years, due in part to lack of outflows and pollution from agricultural runoff, it has attracted a small, but dedicated population. The sea itself offers recreational opportunities including boating, camping, off-roading, hiking, use of personal watercraft, photography and bird watching. The sea has been termed a "crown jewel of avian biodiversity," being a major resting stop on the Pacific Flyway, a migratory path for birds. 2 Days Adrift the Salton Sea includes two nights accommodations at the Bombay Beach Inn, boat rental at the Salton City Harbor, and a guided fishing tour.',
    'Boating in the Salton Sea Harbor, Guided fishing tour, Bird watching, Accommodations at the Bombay Beach Inn, Unique cuisine featuring local seafood',
    'Easy',
    '2 days',
    '350',
    'Southern California',
    'Boating, Fishing, Bird watching, Desert, Sea, Eco-Tour'
),
(
    'KC',
    'Kids L.A. Tour',
    'Los Angeles for the young (and young at heart!) Go beyond the concrete jungle and discover just what a playground L.A. can be.',
    'Kids L.A. Tour is a 3-day jam-packed, fun-filled tour of the best the city has to offer- for any age. The first day includes admission to the L.A. Zoo, home to over 1,100 animals, and its companion park, the Long Beach Aquarium. After the little ones are tuckered out, take them back to the Disneyland Hotel in Anaheim so they can rest up for the next two days at the world famous Disneyland Resort. Park Hopper tickets allow you to go between Disneyland and the California Adventure Park, and with Express Passes, you never have to wait in line. Disneyland Hotel guests get exclusive use of the monorail that surrounds the park, and perfect views of the nightly fireworks shows from the hotel. Enjoy meals from any of the Disneyland cafes or leave the kids for an evening and enjoy a meal at one of Downtown Disney''s more upscale restaurants. This is a family vacation- California style.',
    'Admission to the L.A. Zoo and Long Beach Aquarium, 2 nights at the Disneyland Hotel, 3 day luxury car rental, Park Hopper tickets for Disneyland and California Adventure, Free parking',
    'Easy',
    '3 days',
    '1200',
    'Southern California',
    'Kid friendly, Museum,  Animals, Theme park'
),
(
    'NW',
    'Endangered Species Expedition',
    'California boasts the largest number of unique species in the continental United States, which makes a “natural” destination for nature lovers. For those who want to get a glimpse of California’s at-risk flora and fauna, and our efforts to preserve it, take the Endangered Species Expedition.',
    'Taking a cue from the Nature Conservancy, we’ve selected 15 state parks and preserves that are shining examples of conservation in action. Just one example is the Guadalupe-Nipomo Dunes Preserve, 18 miles of Earth''s most biodiversity coastal dune-lagoon ecosystem. Activities include camping, hiking, horseback riding, boating and bird watching. The tour package includes 2 nights of camping and 3 days admission to the park of your choice. We can also arrange for RV rentals. This is a great package for families who want to pass down a great experience and an education to the next generation, while participating in preserving a part of their future.',
    'Visit any one of 15 of California''s best state parks, Camping, Hiking, Horseback riding, Boating, Bird watching, RV rentals available',
    'Medium',
    '3 days',
    '600',
    '0',
    'Eco Tour, Camping, Animals, Boating, Hiking'
),
(
    'SC',
    'Mammoth Mountain Adventure',
    'With over 400 inches of annual snowfall, Mammoth Mountain turns winter into a 3 season event! Learn to ski, snowboard or even snowshoe across the thousands of acres of this winter wonderland.',
    'The Mammoth Mountain Adventure is 4 days of wild, winter fun. Take a lesson the first day from the Ski & Snowboard School, led by grizzly pro instructors. This tour includes a 4 full day lift pass, so when you''re ready, you can take on any one of the 150 trails over Mammoth''s epic terrain. Equipment rentals are included, so you can pack light. Need a break? Take a scenic gondola to the summit of Mammoth Mountain, 11,000 feet in all, or take a Snowcat tour of the backcountry. Enjoy dinners at the Mammoth Mountain Inn, a snowball''s throw from the main lodge, where you''ll also be provided 3 night''s complimentary lodging. This package is available October through early June, but lift tickets are rare, so book now.',
    '4 day lift ticket, 2 hour lesson at the Mammoth Ski & Snowboard School, Gondola rides to the summit, Snowcat tours, Private suite at the Mammoth Mountain Inn',
    'Difficult',
    '4 days',
    '800',
    'Southern California',
    'Skiing, Snowboarding, Cabin, Hiking, Mountains'
),
(
    'TC',
    'Oranges & Apples Tour',
    'This three day tour is a taste of some of California''s finest fruits. The first day features apple picking, a smoking barbeque and a hayride at a small farm in the historic Oak Glen, and the second take you''ll drive to sample the only growing place in the world for pixie tangerines, Ojai, California.',
    'Oak Glen is a tiny hamlet located in the foothill of the San Bernadino Mountain, only 90 minutes from LA, but the climate makes it perfect for stone fruits, such as pears, peaches, and nectarines. However, the jewel of this town is the apple. You''ll start the day at Riley''s Apple Farm, where you can pick and press as many apples as you can carry. Take a hayride around the farm property and, a fun treat for kids, visit the barn animals. Feast on apple-wood smoked BBQ featuring tri-tip, ribs and chicken apple sausage. Lodging is provided at the quaint Craftin Hills Inn. The next day, it''s a short backwoods drive to Ojai, CA, where you''ll receive a private tour and picnic lunch at the Churchill Brenneis Orchard. Owners Jim Churchill and Lisa Brenneis are knowledgeable and warm, and you''ll leave with a glow and the most delicious tiny tangerines you''ve ever tasted. Spend a restful night at the Lavender Inn in beautiful downtown Ojai before returning to the regular pace.',
    'Apple picking and cider pressing, Hayrides around the apple farm, Lunch with apple-wood smoked BBQ, Lodging at two distinct bed and breakfast inns, Walkabout through Ojai''s fragrant orange groves',
    'Easy',
    '3 days',
    '350',
    'Southern California',
    'Tasting, Olive Oil, California History, Picnic, Nature, Farming'
);